"""init reference_range

Revision ID: 94228befb88f
Revises: 
Create Date: 2026-06-11 00:44:01.951960
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94228befb88f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_range',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('biomarker_id', sa.String(length=32), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('lab_source', sa.String(length=64), server_default='Any', nullable=False),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('reference_min', sa.Float(), nullable=True),
    sa.Column('reference_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('specimen_type', sa.String(length=64), server_default='Whole Blood', nullable=False),
    sa.Column('source_guideline', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('M', 'F') OR gender IS NULL", name='ck_reference_range_gender'),
    sa.CheckConstraint('age_max >= age_min', name='ck_reference_range_age_order'),
    sa.CheckConstraint('age_min >= 0', name='ck_reference_range_age_min_nonneg'),
    sa.CheckConstraint('reference_min IS NULL OR reference_max IS NULL OR reference_max >= reference_min', name='ck_reference_range_bounds_order'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biomarker_id', 'gender', 'age_min', 'age_max', 'lab_source', 'condition', name='uq_reference_range_dimensions')
    )
    op.create_index('ix_reference_range_lookup', 'reference_range', ['biomarker_id', 'gender', 'age_min', 'age_max'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reference_range_lookup', table_name='reference_range')
    op.drop_table('reference_range')
    # ### end Alembic commands ###
